Fix gelf enum error
src/infrastructure/logs/transports/gelf.ts(51,26): error TS7015: Element implicitly has an 'any' type because index expression is not of type 'number'.